HRT-28 create course info
HeartUoA/HeaRT pull request #16
Opened 2020-09-14 08:23 UTC by EricPedrido

### Purpose

Adds front end for creating chart/providing course information just before starting the game.

[HRT-28](https://softeng761team5.atlassian.net/browse/HRT-28)

### Approach

- Adds a new page for creating course information
- Form is responsive to window size changes
- Added antd icons to the package. Not sure if it is added in the PR, but if you need to, then it's: 
```javascript 
npm install --save @ant-design/icons
```

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Screenshots before and after this change (required for UI changes)
#### Does this PR involve a UI change?

- [X] Yes
- [ ] No

#### Screenshot(s) of UI before this PR
n/a

#### Screenshot(s) of UI after this PR
![screenshot](https://user-images.githubusercontent.com/43208889/93061366-8fd13a00-f6c7-11ea-914f-347809090e65.PNG)
)

2020-09-22 02:06 UTC, lucycy98 requested changes
hiii looks good 2 things: 
- can you please rebase with master? its a little out of date. 
- are we putting shadows for all page titles? e.g 'create chart'
- when I select an item for course age and cohort size, the text field should be filled with the value I select. currently it is just 'select'. see below:
![image](https://user-images.githubusercontent.com/34847224/93838111-a0436f00-fcdc-11ea-8cff-3c54277260a6.png)

2020-09-22 03:44 UTC, EricPedrido commented
> * can you please rebase with master? its a little out of date.

Yup will do

> * are we putting shadows for all page titles? e.g 'create chart'

This is how it was in the hifi prototypes, but i can remove the shadows for consistency with other pages

> * when I select an item for course age and cohort size, the text field should be filled with the value I select. currently it is just 'select'.

I will need to look into this, I've done it how they've documented on antd's website but I'll try find a fix somewhere online

2020-09-24 03:18 UTC, PreetPatel commented on src/pages/CourseInfo.tsx
> +  };
Think the cards endpoint is now available :)

2020-09-24 03:18 UTC, PreetPatel commented on src/pages/CourseInfo.tsx
> +    // TODO: Write code here to redirect back to homepage
This can also be implemented now

2020-09-25 07:41 UTC, lucycy98 approved these changes
thanks for the changes - LGTM

2020-09-26 01:30 UTC, mitchfaulcon approved these changes
Looks good to me, I'll implement the page routing when I do the play reason ticket

2020-09-26 01:32 UTC, merged