feat(playreason): Play reason page
HeartUoA/HeaRT pull request #54
Opened 2020-10-05 08:07 UTC by mitchfaulcon

### Purpose

Added a new page between the charts dashboard and game itself for the user to enter the reason they are playing the game.

[HRT-49](https://softeng761team5.atlassian.net/browse/HRT-49)

### Approach

- Added radio buttons with an extra text box that appears when "Other" is selected
- Checks to make sure an option is selected. If "Other" is selected, a non-whitespace entry must be provided in the textbox
- The back button on the first dimension of the game routes back to the appropriate page (PlayReason if it's a new chart, charts dashboard page if a chart was clicked on, or the main dashboard if the user manually navigated to the game page)

### Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### Screenshots before and after this change (required for UI changes)

#### Does this PR involve a UI change?

- [x] Yes
- [ ] No

#### Screenshot(s) of UI before this PR

N/A

#### Screenshot(s) of UI after this PR

![image](https://user-images.githubusercontent.com/42291691/95054609-9e52c480-074e-11eb-8db8-da50bdd0f520.png)
![image](https://user-images.githubusercontent.com/42291691/95054632-a6126900-074e-11eb-9ea1-b72113834d97.png)

2020-10-05 08:15 UTC, michellemtan requested changes, later dismissed
Looks good so far - just a few styling things! Could you please put the radio button styling into a css file for the PlayReason page for consistency with the rest of the other pages?

Also, I tried the page on my monitors and it looks good but could you add a bit more spacing between the reasons and the buttons? 

![image](https://user-images.githubusercontent.com/37464749/95055484-d1e21e80-074f-11eb-9916-e87936d5b565.png)

There's quite a bit of room on the card and the buttons are a little close to the reasons

2020-10-05 08:16 UTC, gargi-bansal requested changes
In terms of UI, maybe just keep the text area always visible but disable it initially. Only enable it when other is selected.
And I agree with Michelle. There should be a bit more spacing between the options and the buttons

2020-10-05 09:00 UTC, gargi-bansal commented on src/pages/PlayReason.tsx
> +import { Button, Layout, Select, Typography, Radio } from "antd";
unused import statement

2020-10-05 09:01 UTC, gargi-bansal commented on src/pages/PlayReason.tsx
> +  const { chartID } = useParams<ParamTypes>();
unused variable? I don't think this or the ParamTypes interface is needed at all then?

2020-10-05 09:04 UTC, gargi-bansal commented on src/pages/PlayReason.tsx
> +      <Layout.Content className="Main-Container">
I think you could honestly just use a div here?

2020-10-05 09:09 UTC, gargi-bansal requested changes
UI requests:
- Buttons together should be the same width as the text input
- Padding of 60px applied to whole form
- Consistent font size for the options and text area
- Update all CSS styling in reason of play to be consistent with what is already in master.

2020-10-06 20:57 UTC, gargi-bansal approved these changes

2020-10-10 05:15 UTC, lucycy98 approved these changes
LGTM @mitchfaulcon!

2020-10-10 20:44 UTC, merged